---
 - name: copy this to home page as website
   win_copy:
     src: ../files/index.html
     dest: C:\inetpub\wwwroot\index.html
 - name: deploying the dynamic website
   template:
     src: ../templates/facts.html.j2
     dest: C:\inetpub\wwwroot\facts.html
     
